### PR TITLE
Usage Records support

### PR DESCRIPTION
**Pull request by phayes**
Adds support for Usage Records as per https://stripe.com/docs/api/usage_records

### CODE REVIEW

**Comment by arlyon** [comment]
Hello, apologies for the late reply. We are working on getting up to speed on pull requests. May I ask if you are still interested in merging this (we are!) that you rebase? Thank you.

**Comment by phayes** [comment]
Hi @arlyon, 

Yes I'll rebase my PRs.  It might take a few days for me to get to it!

**Comment by phayes** [comment]
This is now rebased.

**Review by seanpianka — APPROVED** [review]

**Comment by phayes** [comment]
I've rebased again and added additional support for usage record summaries (https://stripe.com/docs/api/usage_records/subscription_item_summary_list)

**Comment by seanpianka** [comment]
Thanks for the PR!

**Pull request merged**
