### PR TITLE
Migrate to reqwest

### LINKED ISSUE #9: Switch from `hyper 0.10.x` to `reqwest`
For the synchronous version of `stripe-rs` (e.g. not `tokio-stripe` or however we decided to implement an async-friendly api) it looks like `reqwest` is the most well-loved blocking http client in the rust community.

We should switch to it so we stop depending on an old version of hyper which itself depends on other older dependency versions.

### PR DESCRIPTION
**Pull request by lutostag**
Move to reqwest for sync client, which closes #9.

Any feedback is welcome.

Thanks!

### CODE REVIEW

**Comment by lutostag** [comment]
@kestred, yep all cleaned up.
Should be good for any additional testing you want to throw at it.

Thanks for shepherding #16 and this one through so far! :heart:

**Comment by kestred** [comment]
Didn't find anything wrong in testing, so I'll merge it in-- Thanks for the PR! 🎉

**Comment by kestred** [comment]
I'll bump the minor version and publish a new crate today with this, and the other recently accumulated changes.

**Comment by kestred** [comment]
fyi, both changes deployed as part of `0.6.0`

**Pull request merged**
