### PR TITLE
Feature/livemode signature

### PR DESCRIPTION
**Pull request by busarovalex**

### CODE REVIEW

**Comment by busarovalex** [comment]
The main problem with Webhook::construct_event was that it was using indexing, which may cause panic. This could lead to dos when receiving incorrect headers

**Comment by busarovalex** [comment]
I guess some garbage commits fell into this pr. If the contents is ok, I will close this one and create another, clean pr :)

**Comment by busarovalex** [comment]
Another, better pr will be coming soon

**Comment by kestred** [comment]
Thanks! I look forward to it.

**Comment by mikeumus** [comment]
@busarovalex is this code required to do test webhooks with `stripe-rs`? 

I'm trying to parse a webhook event with @seenickcode's code here but am getting `BadSignature` error:
https://github.com/wyyerd/stripe-rs/issues/166#issue-829434939

``` bash 
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: BadSignature', src/stripe_webhook.rs:63:69
```

This is my line 63 referenced in the error:
``` rust
let secret = env::var("STRIPE_API_SECRET_KEY").unwrap();
let event = Webhook::construct_event(payload_str, sig, &secret).unwrap();
```

**Comment by seenickcode** [comment]
@mikeumus not sure this helps but here's the top of my webhook handler. 

```
pub async fn stripe_webhook(
    req: HttpRequest,
    data: web::Data<AppData>,
    pool: web::Data<DbPool>,
    payload: web::Bytes,
) -> Result<HttpResponse, AppError> {
    // deserialize Stripe event
    let payload_str = std::str::from_utf8(payload.borrow()).map_err(|e| {
        AppError::InternalError(format!(
            "failed to convert stripe event payload, {}: {:?}",
            e, payload,
        ))
    })?;

    let sig = get_header_value(&req, "Stripe-Signature").unwrap_or_default();
    let secret = data.stripe_webhook_secret.clone();

    let event = Webhook::construct_event(payload_str, sig, &secret[..]).map_err(|e| {
        AppError::InternalError(format!(
            "failed to validate stripe event, {}: {}",
            e, payload_str
        ))
    })?;

    info!("got stripe event {:?}", event.clone());

    ...
```

[https://stripe.com/docs/webhooks/signatures](https://stripe.com/docs/webhooks/signatures)

**Comment by mikeumus** [comment]
@seenickcode does this work in test mode for you too?

**Comment by seenickcode** [comment]
Of course it should work in any environment test or production

On May 4, 2021, Sean Pianka ***@***.***> wrote:
> @seenickcode <https://github.com/seenickcode> does this work in test
> mode for you too?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wyyerd/stripe-rs/pull/49#issuecomment-831954908>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAASQOOFRLQ4EANXIVXDUCLTL73FRANCNFSM4GTPKXMQ>.

**Comment by mikeumus** [comment]
@seenickcode with localhost webhooks via the stripe CLI like this?

``` bash
stripe listen --forward-to localhost:17001/webhook --events invoice.payment_succeeded
```

**Comment by seenickcode** [comment]
> If so, what's @busarovalex's PR here about?
> 
> @seenickcode have you used it with localhost webhooks via the stripe CLI like this?
> 
> ```shell
> stripe listen --forward-to localhost:17001/webhook --events invoice.payment_succeeded
> ```
> 
> It's no dice for me. I'll keep digging.
> Thank you 🙇🏻‍♂️

I haven’t gotten around to trying it with the CLI. I use ngrok 

If you’re still getting a bad signature error message then it might be your code. Have you tried my snippet? Is your handler even firing?

**Comment by mikeumus** [comment]
@seenickcode yeah that's how I was able to get the output in the last reply:

> click to expand:
failed to validate stripe event, error comparing signatures: {

https://github.com/wyyerd/stripe-rs/pull/49#issuecomment-831954908

**Comment by mikeumus** [comment]
@seenickcode I was using my STRIPE SECRET API KEY instead of the Webhook Secret 🤦🏻‍♂️
It's working now. 

Thank you for the replies & assists 🙇🏻‍♂️

**Pull request closed without merging**
